### ISSUE TITLE
Version Divergance

### ISSUE THREAD

**Issue by tlhunter** [opentable/spur-config#16]
Version 0.1.2 in this repo exists in a tag, but is not in master.

The README in this repo seems to be different than the README used on NPM:
https://www.npmjs.com/package/spur-config

The one in this repo uses .coffee examples, the one on npmjs uses .js examples.

The one on npmjs has some coffeescript syntax intermixed with the js:

``` javascript
module.exports = function() {

  # Extend multiple files // wrong comment
  this.extends('default', 'shared-deployed');

  return this.properties({
    environment: 'production',
    port: process.env.PORT or 9000 // no or's
  });

}
```

**Comment by acolchado** [comment]
@tlhunter It should be consistent now. Seems like a tag or two were not pushed up.
